# 市场仓库
市场仓库=https://github.com/MonthZifang/mdt-Plugin-Market.git
市场分支=main
市场缓存目录=market-cache
插件缓存目录=plugin-cache
安装目录=config/mods
市场配置文件=market.json
仓库登记后缀=.repo.json
插件元数据文件=market.plugin.json

# 行为
自动同步=true
允许强制安装=true
